name: Java Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test
        env:
          MY_APP_PASSWORD: ${{ secrets.MY_APP_PASSWORD }}